services:
  # Configuración del NameNode de Hadoop
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: hadoop-namenode
    environment:
      - CLUSTER_NAME=test-cluster
      - CORE_CONF_fs_defaultFS=hdfs://hadoop-namenode:9000
    ports:
      - "9870:9870"
      - "9000:9000"  
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    networks:
      - hadoop_network
    depends_on:
      - zookeeper
      - kafka


  # Configuración del DataNode de Hadoop
  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: hadoop-datanode
    environment:
      - CLUSTER_NAME=test-cluster
      - CORE_CONF_fs_defaultFS=hdfs://hadoop-namenode:9000
    ports:
      - "9864:9864"
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    networks:
      - hadoop_network
    depends_on:
      - namenode


  # Configuración de Zookeeper 
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    ports:
      - "2181:2181" 
    networks:
      - hadoop_network

  # Configuración de Kafka
  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka-new
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENER_SECURITY_PROTOCOL=PLAINTEXT
      - KAFKA_LISTENER_NAME_INTERNAL=INTERNAL
      - KAFKA_LISTENER_PORT_INTERNAL=9093
    ports:
      - "9092:9092"  
    networks:
      - hadoop_network
    depends_on:
      - zookeeper

  # Configuración del container del Consumer
  consumer:
    image: python:3.10-slim  
    container_name: consumer-container
    networks:
      - hadoop_network
    volumes:
      - ./consumer.py:/app/consumer.py
    environment:
      - KAFKA_BROKER=kafka:9092
      - HADOOP_NAMENODE=hadoop-namenode:9870
    command: [ "python", "/app/consumer.py" ]  
    depends_on:
      - kafka
      - namenode

volumes:
  hadoop_namenode:
  hadoop_datanode:

networks:
  hadoop_network:
    driver: bridge
